### ISSUE TITLE
Add preview or production environment .

### ISSUE THREAD

**Issue by mwenku** [MaximilianHagelstam/privatevoid#66]

**Comment by hagelstam** [comment]
This project is not done yet, but when it is I will definetly deploy it. I am hoping to finnish this project by the 14th of July

**Comment by mwenku** [comment]
Alright I wanted to check it out and help if possible . But I'll just clone it and run it locally.

**Comment by mwenku** [comment]
I'll run locally

**Comment by ghost** [comment]
Happy over 14th of July! Where is it?
